Repository dakshsinghrathore/Brighter-Beginnings, pull requests merged in 2024-01, with the labels that each got.

#39 Feat: Improved the register page
  dist/register.html
  dist/style.css
Labels: enhancement, SWOC S4, Medium

#47 Update index.html
  dist/index.html
Labels: bug, SWOC S4, Easy

#50 Fixed menu-items overflowing underline
  dist/index.html
  dist/style.css
Labels: bug, SWOC S4, Easy

#58 feat: added more courses in m3
  dist/development.html
Labels: enhancement, good first issue, SWOC S4, Easy

#91 fix: menu button does not work on first click
  dist/index.html
Labels: good first issue, SWOC S4, Easy

#100 anchored our teams with github contributors page
  dist/index.html
Labels: enhancement, SWOC S4, Beginner

#108 Added dropdown effect to profile picture
  dist/logic.html
  dist/script.js
  dist/style.css
Labels: enhancement, SWOC S4

#120 Added hovering effect in Get started page
  dist/style.css
Labels: enhancement, SWOC S4, Medium

#133 git commit -m "fix: color discrepancy"
  dist/about.html
  dist/development.html
  dist/logic.html
  dist/problemsolving.html
Labels: bug, SWOC S4, Beginner

#135 feat:Added validations to all the fields present in the Registration page.
  .vscode/settings.json
  dist/register.css
  dist/register.html
Labels: enhancement, SWOC S4, Medium

#131 Added kwargs and args of python to problem solving page
  dist/problemsolving.html
Labels: documentation, SWOC S4, Easy

#122 Fixed Typo errors
  dist/problemsolving.html
Labels: bug, SWOC S4, Beginner

#137 feat:Added Validations to the Newsletter and Confirmation Popup
  dist/about.html
  dist/feedback.html
Labels: enhancement, SWOC S4, Easy

#138 Improved styling of Nav and footer tag links
  dist/index.html
Labels: enhancement, SWOC S4, Beginner

#146 About Us Page Horizontal Bar
  dist/about.html
Labels: good first issue, SWOC S4, Easy
